[package]
name = "far_travels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_asset_loader = "0.16.0"
rand = "0.8.5"
seldom_fn_plugin = "0.3.0"
